dag:
  dag_id: app-categorization-full-cycle
  schedule_interval: '0 0 10,16,23,L * *'  # Scheduled at specific times and on the last day of the month
  tags: ['app', 'categorization']
  catchup: false
  default_args:
    owner: airflow
    depends_on_past: false
    start_date: '2022-05-08T00:00:00'
    email: farshid_hossein@ada-asia.com
    email_on_failure: true
    email_on_retry: false
    http_conn_id: 'teams_notification_webhook'

# EMR Configuration
emr_release: 'emr-5.31.0'  # EMR version
emr_log_path: 's3://aws-logs-331041401449-us-east-1/elasticmapreduce/'
emr_packages: 'org.apache.spark:spark-avro_2.11:2.4.6,org.apache.hadoop:hadoop-aws:2.10.1'
emr_bootstrap:
  - Name: household_bootstrap
    ScriptBootstrapAction:
      Path: "s3://ada-dev/app_category/bootstrap/pre-install_ts.sh"

# EC2 Configuration
ec2_key: &ec2_key 'emr_key'
ec2_subnet: &ec2_subnet
  - subnet-ea341ba1  # AZ: us-east-1a
  - subnet-88c0a8d5  # AZ: us-east-1b
  - subnet-513ee536  # AZ: us-east-1c

# Security Groups
service_sg: &service_sg 'sg-6ef90a18'
slave_sg: &slave_sg 'sg-4c8c7f3a'
master_sg: &master_sg 'sg-19f6056f'

# Cluster Configuration
cluster_config: &cluster_config
  - Classification: spark-env
    Properties: {}
    Configurations:
      - Classification: export
        Properties:
          PYSPARK_PYTHON: "/usr/bin/python3"

# Spot Instance Fleets
large-spot:
  instance_type:
    Ec2KeyName: *ec2_key
    Ec2SubnetIds: *ec2_subnet
    InstanceFleets:
      - Name: Masterfleet
        InstanceFleetType: MASTER
        TargetSpotCapacity: 1
        LaunchSpecifications:
          SpotSpecification:
            TimeoutDurationMinutes: 30
            TimeoutAction: SWITCH_TO_ON_DEMAND
        InstanceTypeConfigs:
          - InstanceType: r6g.xlarge
            BidPriceAsPercentageOfOnDemandPrice: 70
      - Name: Corefleet
        InstanceFleetType: CORE
        TargetSpotCapacity: 16
        LaunchSpecifications:
          SpotSpecification:
            TimeoutDurationMinutes: 30
            TimeoutAction: SWITCH_TO_ON_DEMAND
        InstanceTypeConfigs:
          - InstanceType: r6g.4xlarge
            BidPriceAsPercentageOfOnDemandPrice: 70
      - Name: Taskfleet
        InstanceFleetType: TASK
        TargetSpotCapacity: 12
        LaunchSpecifications:
          SpotSpecification:
            TimeoutDurationMinutes: 30
            TimeoutAction: SWITCH_TO_ON_DEMAND
        InstanceTypeConfigs:
          - InstanceType: r6g.4xlarge
            BidPriceAsPercentageOfOnDemandPrice: 70
    TerminationProtected: false
    KeepJobFlowAliveWhenNoSteps: false
    ServiceAccessSecurityGroup: *service_sg
    EmrManagedSlaveSecurityGroup: *slave_sg
    EmrManagedMasterSecurityGroup: *master_sg
  cluster_config: *cluster_config
  steps_config:
    num-executors: '44'
    driver-memory: '32G'
    driver-cores: '5'
    executor-memory: '32G'
    executor-cores: '5'

large-spot-x:
  instance_type:
    Ec2KeyName: *ec2_key
    Ec2SubnetIds: *ec2_subnet
    InstanceFleets:
      - Name: Masterfleet
        InstanceFleetType: MASTER
        TargetSpotCapacity: 1
        LaunchSpecifications:
          SpotSpecification:
            TimeoutDurationMinutes: 30
            TimeoutAction: SWITCH_TO_ON_DEMAND
        InstanceTypeConfigs:
          - InstanceType: r6g.4xlarge
            BidPriceAsPercentageOfOnDemandPrice: 95
      - Name: Corefleet
        InstanceFleetType: CORE
        TargetSpotCapacity: 16
        LaunchSpecifications:
          SpotSpecification:
            TimeoutDurationMinutes: 30
            TimeoutAction: SWITCH_TO_ON_DEMAND
        InstanceTypeConfigs:
          - InstanceType: r6g.4xlarge
            BidPriceAsPercentageOfOnDemandPrice: 95
      - Name: Taskfleet
        InstanceFleetType: TASK
        TargetSpotCapacity: 10
        LaunchSpecifications:
          SpotSpecification:
            TimeoutDurationMinutes: 30
            TimeoutAction: SWITCH_TO_ON_DEMAND
        InstanceTypeConfigs:
          - InstanceType: r6g.4xlarge
            BidPriceAsPercentageOfOnDemandPrice: 95
    TerminationProtected: false
    KeepJobFlowAliveWhenNoSteps: false
    ServiceAccessSecurityGroup: *service_sg
    EmrManagedSlaveSecurityGroup: *slave_sg
    EmrManagedMasterSecurityGroup: *master_sg
  cluster_config: *cluster_config

# Tags for EMR
emr_tag:
  - Key: Environment
    Value: Test
  - Key: Department
    Value: BI
  - Key: Name
    Value: app-categorization
  - Key: Project
    Value: Others-affluence
  - Key: Engineer
    Value: farshid.hossein@ada-asia.com
  - Key: JiraNo
    Value: DS-524

# EMR Roles
ServiceRole: EMR_ServiceRole
JobFlowRole: EMR_EC2_ADARole

# Athena Configuration
athena_database: 'farshid_db'
athena_output: 's3://ada-dev/app_category/athena/'
athena_workgroup: 'business-insights'
table_persona_v1: 'ref_personas_v1'
table_persona_v2: 'ref_personas_v2'

# S3 Path for Scripts
S3_PATH_CODE: 's3://ada-dev/app_category/script/'

# Project Data Paths
project_data:
  input_agg: 's3://ada-prod-data/etl/data/brq/agg/agg_brq/daily/'
  app_list_file: 's3://ada-prod-ml/data/app_category/results/'
  app_list_file_not_found: 's3://ada-dev/app_category/ref/app_list/'
  scrap_result: 's3://ada-prod-ml/data/app_category/results/'
  ref_app_path: 's3a://ada-business-insights/data/reference/ref_intermediate/ref_app.csv'
  ref_persona_path: 's3a://ada-business-insights/data/reference/ref_persona_rank.csv'
  temp_result: 's3://ada-dev/app_category/temp_result/'
